### PR TITLE
Compatibility check and added darkroom mode to brightness controller

### PR DESCRIPTION
**Pull request by mariokorte**
- Compatibility check added to give the user information about problems on some devices
- Using the findings of @milch I added a darkroom mode to the brightness controller (Manual selection and new option when turning brightness too low)

### CODE REVIEW

**Comment by mariokorte** [comment]
Did the cleanup. Should be ready for pull now.

**Comment by anthonya1999** [comment]
@mariokorte the reason behind the _framebufferConnection variable is so we don't have to declare it within methods each time.

**Comment by mariokorte** [comment]
So you just want to initialize it once as a static and reuse it?

**Comment by anthonya1999** [comment]
@mariokorte exactly.

**Comment by mariokorte** [comment]
@anthonya1999 The IOMobileFramebufferGetColorRemapMode is needed because I need to know if a change in ColorRemapMode has been performed (a.k.a. 'was the screen already inverted before?') to either set the GammaTable or not afterwards.

**Comment by anthonya1999** [comment]
@mariokorte ah I see, sorry. I was under the impression that you were only using it as a preliminary function to set the color remap mode.

**Comment by mariokorte** [comment]
I hope this is how you intended it? Please check.

**Comment by anthonya1999** [comment]
@mariokorte looks good! Thanks

**Pull request merged**
